# Benchmark models for Grid level

In [1]:
import sys
sys.path.insert(0, '../')

import src.utils as util
import src.calculate_errors as err
import constants as const

%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

In [3]:
from sktime.forecasting.ets import AutoETS
# from sktime.forecasting.bats import TBATS
from sktime.forecasting.arima import AutoARIMA

In [46]:
data = pd.read_csv(f'../ts_data/6010.csv', index_col=[0])

In [47]:
data.loc[data['power'] < 0]

Empty DataFrame
Columns: [power, wind, temperature, dewPoint, cloudCover, humidity, pressure, uvIndex, wind_1, temperature_1, dewPoint_1, cloudCover_1, humidity_1, pressure_1, uvIndex_1, wind_2, temperature_2, dewPoint_2, cloudCover_2, humidity_2, pressure_2, uvIndex_2, wind_3, temperature_3, dewPoint_3, cloudCover_3, humidity_3, pressure_3, uvIndex_3, wind_4, temperature_4, dewPoint_4, cloudCover_4, humidity_4, pressure_4, uvIndex_4, wind_5, temperature_5, dewPoint_5, cloudCover_5, humidity_5, pressure_5, uvIndex_5, wind_6, temperature_6, dewPoint_6, cloudCover_6, humidity_6, pressure_6, uvIndex_6, wind_7, temperature_7, dewPoint_7, cloudCover_7, humidity_7, pressure_7, uvIndex_7, wind_8, temperature_8, dewPoint_8, cloudCover_8, humidity_8, pressure_8, uvIndex_8, wind_9, temperature_9, dewPoint_9, cloudCover_9, humidity_9, pressure_9, uvIndex_9, wind_10, temperature_10, dewPoint_10, cloudCover_10, humidity_10, pressure_10, uvIndex_10, wind_11, temperature_11, dewPoint_11, cloudCover_11, humidity_11, pressure_11, uvIndex_11, wind_12, temperature_12, dewPoint_12, cloudCover_12, humidity_12, pressure_12, uvIndex_12, wind_13, temperature_13, dewPoint_13, cloudCover_13, humidity_13, pressure_13, uvIndex_13, wind_14, ...]
Index: []

[0 rows x 106 columns]

In [6]:
look_back = 14 * 7  # 14 hours in to 7 days
# train, val, test split
train, val, test = util.split_hourly_data(data, look_back)

In [7]:
fh = np.arange(14) + 1

In [8]:
fh

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# ARIMA

In [15]:
test_series = pd.Series(test[look_back:]['power'].values)

In [9]:
train_series = pd.Series(train['power'].values)

In [11]:
forecaster =  AutoARIMA(sp=14, suppress_warnings=True, trace = True)
forecaster.fit(train_series)
y_pred = forecaster.predict(fh)

Performing stepwise search to minimize aic
 ARIMA(2,1,2)(1,0,1)[14] intercept   : AIC=82656.279, Time=10.21 sec
 ARIMA(0,1,0)(0,0,0)[14] intercept   : AIC=86828.301, Time=0.11 sec
 ARIMA(1,1,0)(1,0,0)[14] intercept   : AIC=83942.912, Time=1.00 sec
 ARIMA(0,1,1)(0,0,1)[14] intercept   : AIC=84851.085, Time=1.15 sec
 ARIMA(0,1,0)(0,0,0)[14]             : AIC=86826.302, Time=0.05 sec
 ARIMA(2,1,2)(0,0,1)[14] intercept   : AIC=83002.083, Time=9.63 sec
 ARIMA(2,1,2)(1,0,0)[14] intercept   : AIC=82999.389, Time=9.49 sec
 ARIMA(2,1,2)(2,0,1)[14] intercept   : AIC=82662.060, Time=28.69 sec
 ARIMA(2,1,2)(1,0,2)[14] intercept   : AIC=82658.434, Time=24.41 sec
 ARIMA(2,1,2)(0,0,0)[14] intercept   : AIC=83096.503, Time=3.22 sec
 ARIMA(2,1,2)(0,0,2)[14] intercept   : AIC=82948.464, Time=35.74 sec
 ARIMA(2,1,2)(2,0,0)[14] intercept   : AIC=inf, Time=42.69 sec
 ARIMA(2,1,2)(2,0,2)[14] intercept   : AIC=inf, Time=31.71 sec
 ARIMA(1,1,2)(1,0,1)[14] intercept   : AIC=inf, Time=11.53 sec
 ARIMA(2,1,1)(1,

In [72]:
forecaster

AutoARIMA(sp=14, suppress_warnings=True, trace=True)

Check with pmdarima

In [40]:
from pmdarima import auto_arima

In [66]:
data.iloc[:, 0].values[0:100]

array([7.220000e+00, 3.520000e+00, 1.784060e+03, 4.053400e+02,
       1.623232e+04, 2.326704e+04, 2.816688e+04, 2.938593e+04,
       2.592064e+04, 2.052662e+04, 2.401799e+04, 2.280440e+04,
       1.627074e+04, 8.503380e+03, 4.370000e+00, 2.320000e+00,
       1.836860e+03, 8.286030e+03, 1.564794e+04, 2.298999e+04,
       2.799102e+04, 3.033929e+04, 3.076921e+04, 3.028986e+04,
       2.844307e+04, 2.368641e+04, 1.649783e+04, 8.636240e+03,
       6.130000e+00, 3.430000e+00, 5.218500e+02, 7.987260e+03,
       9.193460e+03, 8.793710e+03, 9.973850e+03, 1.010616e+04,
       9.216950e+03, 8.493740e+03, 1.024442e+04, 1.142906e+04,
       1.003188e+04, 3.729940e+03, 1.430000e+00, 6.500000e-01,
       9.235700e+02, 3.592280e+03, 1.567526e+04, 1.703402e+04,
       2.671945e+04, 3.187269e+04, 3.250274e+04, 3.221833e+04,
       3.021931e+04, 2.515554e+04, 1.731551e+04, 8.716740e+03,
       3.200000e-01, 2.300000e-01, 1.748390e+03, 7.882250e+03,
       1.690552e+04, 2.405457e+04, 2.903128e+04, 3.1172

In [67]:
data.iloc[:,1:8].values[0:100]

array([[3.2000e+00, 2.1920e+01, 1.9280e+01, 2.1000e-01, 8.5000e-01,
        1.0112e+03, 0.0000e+00],
       [3.1700e+00, 2.2550e+01, 1.9480e+01, 0.0000e+00, 8.3000e-01,
        1.0115e+03, 0.0000e+00],
       [3.5100e+00, 2.3090e+01, 1.9690e+01, 0.0000e+00, 8.1000e-01,
        1.0119e+03, 0.0000e+00],
       [4.0000e+00, 2.3980e+01, 1.9830e+01, 0.0000e+00, 7.8000e-01,
        1.0123e+03, 0.0000e+00],
       [4.2400e+00, 2.5350e+01, 2.0250e+01, 0.0000e+00, 7.3000e-01,
        1.0123e+03, 2.0000e+00],
       [4.0500e+00, 2.7970e+01, 2.0730e+01, 1.0000e-02, 6.5000e-01,
        1.0127e+03, 4.0000e+00],
       [3.1000e+00, 2.9810e+01, 2.1050e+01, 1.0000e-02, 5.9000e-01,
        1.0122e+03, 8.0000e+00],
       [2.7200e+00, 3.0750e+01, 2.1540e+01, 2.0000e-02, 5.8000e-01,
        1.0117e+03, 1.0000e+01],
       [3.5900e+00, 3.0980e+01, 2.1560e+01, 2.0000e-02, 5.7000e-01,
        1.0112e+03, 1.2000e+01],
       [5.1200e+00, 3.0470e+01, 2.1350e+01, 3.0000e-02, 5.8000e-01,
        1.0107e+03, 1.2

In [68]:
model = auto_arima(data.iloc[:, 0].values[0:100],data.iloc[:,1:8].values[0:100],
                    seasonal=True,
                    m=14, trace=True,
                    error_action='ignore',
                    suppress_warnings=True)

Performing stepwise search to minimize aic
 ARIMA(2,0,2)(1,0,1)[14] intercept   : AIC=1966.432, Time=0.93 sec
 ARIMA(0,0,0)(0,0,0)[14] intercept   : AIC=2005.982, Time=0.02 sec
 ARIMA(1,0,0)(1,0,0)[14] intercept   : AIC=1976.156, Time=0.27 sec
 ARIMA(0,0,1)(0,0,1)[14] intercept   : AIC=1980.671, Time=0.13 sec
 ARIMA(0,0,0)(0,0,0)[14]             : AIC=2003.982, Time=0.27 sec
 ARIMA(2,0,2)(0,0,1)[14] intercept   : AIC=1964.727, Time=0.46 sec
 ARIMA(2,0,2)(0,0,0)[14] intercept   : AIC=1963.386, Time=0.16 sec
 ARIMA(2,0,2)(1,0,0)[14] intercept   : AIC=1964.639, Time=0.44 sec
 ARIMA(1,0,2)(0,0,0)[14] intercept   : AIC=1986.297, Time=0.09 sec
 ARIMA(2,0,1)(0,0,0)[14] intercept   : AIC=1978.817, Time=0.32 sec
 ARIMA(3,0,2)(0,0,0)[14] intercept   : AIC=inf, Time=0.35 sec
 ARIMA(2,0,3)(0,0,0)[14] intercept   : AIC=inf, Time=0.30 sec
 ARIMA(1,0,1)(0,0,0)[14] intercept   : AIC=1986.704, Time=0.06 sec
 ARIMA(1,0,3)(0,0,0)[14] intercept   : AIC=1984.433, Time=0.14 sec
 ARIMA(3,0,1)(0,0,0)[14] inte

In [73]:
model.predict(14, data.iloc[:,1:8].values[100:114]).tolist()

[2153.9864638367817,
 6931.180740323843,
 13800.481486818664,
 17893.676456408117,
 18117.805182270185,
 15607.905090138818,
 12675.73717147828,
 17447.273164522725,
 22337.519155518054,
 24166.370674223464,
 18933.407257196028,
 11013.364061756445,
 3344.327021242628,
 2952.391125824097]

In [71]:
model

ARIMA(order=(2, 0, 2), scoring_args={}, seasonal_order=(0, 0, 1, 14),
      suppress_warnings=True, with_intercept=False)

## Prophet

In [3]:
data = pd.read_csv(f'../ts_data/grid.csv', index_col=[0])

In [6]:
new_data = data.reset_index().rename(columns = {'date_str': 'DS', 'power': 'y'})

In [7]:
new_data

DS          y
0     2020-02-13 07:00:00      12.82
1     2020-02-13 08:00:00       8.69
2     2020-02-13 09:00:00   13068.87
3     2020-02-13 10:00:00    2788.11
4     2020-02-13 11:00:00  131494.69
...                   ...        ...
5133  2021-02-13 16:00:00  255891.15
5134  2021-02-13 17:00:00  231299.38
5135  2021-02-13 18:00:00  255489.24
5136  2021-02-13 19:00:00  191863.39
5137  2021-02-13 20:00:00   92640.43

[5138 rows x 2 columns]