## LSTM and CNN results comparison

1. We will first calculate the error for each time series
2. Then we will calculate the error for each level in the hierarchy
3. Then we will calculate get the forecasts at the grid level
4. Finally we will calculate the error for the grid level

In [3]:
import sys
sys.path.insert(0, '../')

import src.utils as util
import src.calculate_errors as err
import constants as const

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [65]:
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)

In [19]:
import pandas as pd
import numpy as np

In [156]:
def calculate_errors_per_ts(model_path, ts):
    data = pd.read_csv(f'../ts_data/{ts}.csv', index_col=[0])
    look_back = 14 * 7  # 14 hours in to 7 days

    # train, val, test split
    train, val, test = util.split_hourly_data(data, look_back)
    train_df = train[['power']]
    denom = err.calculate_denom(train_df, const.H_SEASONALITY)
    
    results_df = pd.read_csv(f'../{model_path}/final_results/{ts}.csv', index_col=[0])
    test_sample = results_df[['power']].values
    forecasts = results_df[['average_fc']].values
    horizon = 14
    
    mean_mase, error_dist = err.test_errors(train_df, test_sample, forecasts, horizon, const.H_SEASONALITY, denom)
    return mean_mase, error_dist

In [152]:
def get_results_ts(model_path):
    ts_mase = {}
    ts_dist_err = {}
    mase_vals = []

    for ts in const.TS:
        mean_mase_ts, ts_dist = calculate_errors_per_ts(model_path, ts)
        ts_dist_err[ts] = ts_dist
        ts_mase[ts] = mean_mase_ts
        mase_vals.append(mean_mase_ts)
    return ts_mase, ts_dist_err, mase_vals

In [153]:
lstm_mase_ts, lstm_dist_ts, mase_vals_lstm = get_results_ts('lstm_results')

[[1.1510000e+01]
 [2.8276100e+03]
 [1.9125990e+04]
 [8.1339200e+04]
 [1.2024884e+05]
 [1.3811228e+05]
 [1.9399809e+05]
 [1.9819970e+05]
 [2.2189865e+05]
 [2.2080624e+05]
 [2.0887537e+05]
 [2.2511379e+05]
 [1.6983677e+05]
 [9.8231420e+04]
 [9.6800000e+00]
 [1.8740800e+03]
 [1.8753490e+04]
 [5.8166420e+04]
 [1.0881406e+05]
 [1.6862808e+05]
 [2.1315756e+05]
 [2.3728168e+05]
 [2.0340761e+05]
 [2.2100512e+05]
 [2.4627737e+05]
 [2.6660958e+05]
 [2.0890897e+05]
 [1.1731700e+05]
 [6.1400000e+00]
 [2.1617100e+03]
 [2.5827020e+04]
 [5.6276650e+04]
 [1.3592573e+05]
 [2.1774701e+05]
 [2.8107181e+05]
 [3.0989091e+05]
 [2.6460944e+05]
 [2.6301307e+05]
 [2.5103695e+05]
 [2.6334538e+05]
 [2.0689424e+05]
 [1.1586821e+05]
 [5.4100000e+00]
 [2.1333800e+03]
 [2.4505500e+04]
 [8.4336310e+04]
 [1.5555163e+05]
 [2.0885044e+05]
 [2.6058747e+05]
 [3.0631497e+05]
 [3.2316366e+05]
 [3.2781112e+05]
 [3.1204392e+05]
 [2.4286710e+05]
 [2.0408196e+05]
 [1.1715203e+05]
 [5.4000000e+00]
 [1.4632600e+03]
 [1.9166500e+0

[[3.460000e+00]
 [1.076800e+02]
 [1.041060e+03]
 [4.497160e+03]
 [8.179160e+03]
 [1.192987e+04]
 [1.859960e+04]
 [1.816747e+04]
 [1.488139e+04]
 [1.614160e+04]
 [1.228778e+04]
 [1.190281e+04]
 [1.434901e+04]
 [8.407910e+03]
 [2.930000e+00]
 [1.173700e+02]
 [1.031840e+03]
 [3.885150e+03]
 [5.639310e+03]
 [9.715760e+03]
 [1.855836e+04]
 [1.996892e+04]
 [2.000664e+04]
 [2.037684e+04]
 [2.032466e+04]
 [1.881581e+04]
 [1.482448e+04]
 [9.338310e+03]
 [2.880000e+00]
 [6.636000e+01]
 [1.089650e+03]
 [3.456560e+03]
 [1.007773e+04]
 [1.535171e+04]
 [1.897294e+04]
 [2.017390e+04]
 [2.038086e+04]
 [2.038478e+04]
 [2.033893e+04]
 [1.891179e+04]
 [1.494488e+04]
 [9.439580e+03]
 [2.970000e+00]
 [1.285900e+02]
 [1.337430e+03]
 [4.704650e+03]
 [7.781730e+03]
 [9.996630e+03]
 [1.410974e+04]
 [1.952782e+04]
 [2.038361e+04]
 [2.038942e+04]
 [2.035999e+04]
 [1.901276e+04]
 [1.513461e+04]
 [9.487020e+03]
 [2.990000e+00]
 [5.351000e+01]
 [1.065530e+03]
 [4.719620e+03]
 [9.676990e+03]
 [1.497518e+04]
 [1.8767

[[5.260000e+00]
 [2.521400e+02]
 [2.236830e+03]
 [1.078846e+04]
 [1.484639e+04]
 [2.006401e+04]
 [2.949785e+04]
 [2.882422e+04]
 [2.052035e+04]
 [2.473719e+04]
 [1.789200e+04]
 [1.727987e+04]
 [1.864433e+04]
 [9.136700e+03]
 [4.120000e+00]
 [2.112900e+02]
 [1.989480e+03]
 [7.658250e+03]
 [8.722300e+03]
 [1.600867e+04]
 [2.834939e+04]
 [3.158046e+04]
 [3.133179e+04]
 [3.209573e+04]
 [2.991721e+04]
 [2.488234e+04]
 [1.757047e+04]
 [9.380860e+03]
 [7.500000e-01]
 [3.388200e+02]
 [4.413140e+03]
 [5.874870e+03]
 [1.950171e+04]
 [2.621983e+04]
 [3.035138e+04]
 [3.196953e+04]
 [3.241726e+04]
 [3.216133e+04]
 [2.988794e+04]
 [2.506581e+04]
 [1.763164e+04]
 [9.444550e+03]
 [4.400000e-01]
 [3.444500e+02]
 [4.088660e+03]
 [1.163443e+04]
 [1.457019e+04]
 [1.667860e+04]
 [2.310561e+04]
 [3.137096e+04]
 [3.247570e+04]
 [3.222512e+04]
 [3.020988e+04]
 [2.537764e+04]
 [1.792525e+04]
 [9.530020e+03]
 [4.200000e-01]
 [2.519900e+02]
 [4.033760e+03]
 [1.038170e+04]
 [1.890046e+04]
 [2.574891e+04]
 [3.0156

[[3.460000e+00]
 [1.076800e+02]
 [1.041060e+03]
 [4.497160e+03]
 [8.179160e+03]
 [1.192987e+04]
 [1.859960e+04]
 [1.816747e+04]
 [1.488139e+04]
 [1.614160e+04]
 [1.228778e+04]
 [1.190281e+04]
 [1.434901e+04]
 [8.407910e+03]
 [2.930000e+00]
 [1.173700e+02]
 [1.031840e+03]
 [3.885150e+03]
 [5.639310e+03]
 [9.715760e+03]
 [1.855836e+04]
 [1.996892e+04]
 [2.000664e+04]
 [2.037684e+04]
 [2.032466e+04]
 [1.881581e+04]
 [1.482448e+04]
 [9.338310e+03]
 [2.880000e+00]
 [6.636000e+01]
 [1.089650e+03]
 [3.456560e+03]
 [1.007773e+04]
 [1.535171e+04]
 [1.897294e+04]
 [2.017390e+04]
 [2.038086e+04]
 [2.038478e+04]
 [2.033893e+04]
 [1.891179e+04]
 [1.494488e+04]
 [9.439580e+03]
 [2.970000e+00]
 [1.285900e+02]
 [1.337430e+03]
 [4.704650e+03]
 [7.781730e+03]
 [9.996630e+03]
 [1.410974e+04]
 [1.952782e+04]
 [2.038361e+04]
 [2.038942e+04]
 [2.035999e+04]
 [1.901276e+04]
 [1.513461e+04]
 [9.487020e+03]
 [2.990000e+00]
 [5.351000e+01]
 [1.065530e+03]
 [4.719620e+03]
 [9.676990e+03]
 [1.497518e+04]
 [1.8767

[[7.000000e-02]
 [2.782000e+02]
 [1.925040e+03]
 [1.091993e+04]
 [1.698966e+04]
 [1.723632e+04]
 [2.501803e+04]
 [2.133162e+04]
 [2.685292e+04]
 [2.697371e+04]
 [2.662999e+04]
 [1.967893e+04]
 [9.389000e+03]
 [5.342630e+03]
 [1.300000e-01]
 [2.800000e-01]
 [4.900000e-01]
 [7.372790e+03]
 [1.692962e+04]
 [1.696962e+04]
 [1.832654e+04]
 [1.984640e+04]
 [1.970804e+04]
 [1.849186e+04]
 [2.241665e+04]
 [2.143887e+04]
 [1.328089e+04]
 [4.555440e+03]
 [8.000000e-02]
 [2.533800e+02]
 [3.703570e+03]
 [4.336790e+03]
 [1.587061e+04]
 [2.317796e+04]
 [2.618501e+04]
 [2.856427e+04]
 [2.795655e+04]
 [2.915249e+04]
 [2.700725e+04]
 [2.097592e+04]
 [1.318494e+04]
 [4.582870e+03]
 [1.500000e-01]
 [2.217600e+02]
 [3.461000e+03]
 [1.079313e+04]
 [2.022957e+04]
 [2.493538e+04]
 [2.606938e+04]
 [2.584606e+04]
 [2.684168e+04]
 [2.861324e+04]
 [2.684627e+04]
 [1.751657e+04]
 [1.332856e+04]
 [4.763490e+03]
 [7.000000e-02]
 [1.987400e+02]
 [3.550740e+03]
 [1.194656e+04]
 [1.619857e+04]
 [2.100573e+04]
 [2.5205

[[0.000000e+00]
 [1.086820e+03]
 [3.636220e+03]
 [1.696051e+04]
 [2.845754e+04]
 [4.031212e+04]
 [5.200713e+04]
 [5.377900e+04]
 [7.301236e+04]
 [6.410039e+04]
 [6.990940e+04]
 [6.231607e+04]
 [3.808038e+04]
 [2.146635e+04]
 [0.000000e+00]
 [5.715900e+02]
 [5.835970e+03]
 [1.298892e+04]
 [2.769084e+04]
 [4.190502e+04]
 [4.884756e+04]
 [4.196348e+04]
 [5.252441e+04]
 [5.722362e+04]
 [7.629396e+04]
 [6.613327e+04]
 [5.346595e+04]
 [2.602795e+04]
 [0.000000e+00]
 [4.900100e+02]
 [4.112820e+03]
 [1.375278e+04]
 [2.908739e+04]
 [4.536856e+04]
 [6.560325e+04]
 [7.364717e+04]
 [7.767644e+04]
 [7.771519e+04]
 [7.335586e+04]
 [6.600017e+04]
 [5.337519e+04]
 [2.477292e+04]
 [0.000000e+00]
 [4.418000e+02]
 [4.204930e+03]
 [1.759263e+04]
 [3.555840e+04]
 [5.235399e+04]
 [6.498011e+04]
 [7.286813e+04]
 [7.739690e+04]
 [7.939015e+04]
 [7.484650e+04]
 [5.571186e+04]
 [5.244073e+04]
 [2.500674e+04]
 [0.000000e+00]
 [4.258200e+02]
 [4.542790e+03]
 [1.690939e+04]
 [2.720722e+04]
 [4.747153e+04]
 [6.1022

[[1.15000e+00]
 [3.76200e+01]
 [4.01330e+02]
 [1.78118e+03]
 [2.04072e+03]
 [2.84196e+03]
 [4.35120e+03]
 [4.51872e+03]
 [2.96805e+03]
 [3.83281e+03]
 [2.84314e+03]
 [2.62766e+03]
 [2.83246e+03]
 [1.77107e+03]
 [0.00000e+00]
 [3.15700e+01]
 [2.96540e+02]
 [1.16383e+03]
 [1.23640e+03]
 [2.07945e+03]
 [4.11907e+03]
 [4.87162e+03]
 [4.96986e+03]
 [4.90852e+03]
 [4.53926e+03]
 [3.82881e+03]
 [2.87025e+03]
 [1.93043e+03]
 [0.00000e+00]
 [1.37690e+02]
 [1.24636e+03]
 [9.97120e+02]
 [2.76706e+03]
 [3.72160e+03]
 [4.36018e+03]
 [4.76864e+03]
 [4.93728e+03]
 [4.89300e+03]
 [4.52023e+03]
 [3.84480e+03]
 [2.87571e+03]
 [1.93683e+03]
 [0.00000e+00]
 [9.08000e+01]
 [1.04018e+03]
 [1.98947e+03]
 [2.27750e+03]
 [2.44362e+03]
 [3.45634e+03]
 [4.78799e+03]
 [4.97736e+03]
 [4.91231e+03]
 [4.53994e+03]
 [3.87432e+03]
 [2.92106e+03]
 [1.96578e+03]
 [0.00000e+00]
 [9.17400e+01]
 [1.11271e+03]
 [1.87326e+03]
 [2.67535e+03]
 [3.64330e+03]
 [4.33520e+03]
 [4.71662e+03]
 [4.79356e+03]
 [4.60090e+03]
 [4.31124e

[[7.000000e-02]
 [2.782000e+02]
 [1.925040e+03]
 [1.091993e+04]
 [1.698966e+04]
 [1.723632e+04]
 [2.501803e+04]
 [2.133162e+04]
 [2.685292e+04]
 [2.697371e+04]
 [2.662999e+04]
 [1.967893e+04]
 [9.389000e+03]
 [5.342630e+03]
 [1.300000e-01]
 [2.800000e-01]
 [4.900000e-01]
 [7.372790e+03]
 [1.692962e+04]
 [1.696962e+04]
 [1.832654e+04]
 [1.984640e+04]
 [1.970804e+04]
 [1.849186e+04]
 [2.241665e+04]
 [2.143887e+04]
 [1.328089e+04]
 [4.555440e+03]
 [8.000000e-02]
 [2.533800e+02]
 [3.703570e+03]
 [4.336790e+03]
 [1.587061e+04]
 [2.317796e+04]
 [2.618501e+04]
 [2.856427e+04]
 [2.795655e+04]
 [2.915249e+04]
 [2.700725e+04]
 [2.097592e+04]
 [1.318494e+04]
 [4.582870e+03]
 [1.500000e-01]
 [2.217600e+02]
 [3.461000e+03]
 [1.079313e+04]
 [2.022957e+04]
 [2.493538e+04]
 [2.606938e+04]
 [2.584606e+04]
 [2.684168e+04]
 [2.861324e+04]
 [2.684627e+04]
 [1.751657e+04]
 [1.332856e+04]
 [4.763490e+03]
 [7.000000e-02]
 [1.987400e+02]
 [3.550740e+03]
 [1.194656e+04]
 [1.619857e+04]
 [2.100573e+04]
 [2.5205

[[0.00000e+00]
 [3.82700e+01]
 [2.27820e+02]
 [1.03271e+03]
 [1.59747e+03]
 [2.24971e+03]
 [3.34731e+03]
 [3.88837e+03]
 [2.85166e+03]
 [3.14646e+03]
 [2.20251e+03]
 [1.75494e+03]
 [1.67179e+03]
 [9.72020e+02]
 [0.00000e+00]
 [5.08000e+00]
 [2.07920e+02]
 [6.91690e+02]
 [1.22834e+03]
 [2.07096e+03]
 [3.60781e+03]
 [4.10903e+03]
 [4.10427e+03]
 [4.10310e+03]
 [3.67913e+03]
 [3.09175e+03]
 [2.17696e+03]
 [9.25620e+02]
 [0.00000e+00]
 [6.32000e+00]
 [1.78750e+02]
 [6.79870e+02]
 [2.19647e+03]
 [3.13660e+03]
 [3.72304e+03]
 [4.03407e+03]
 [4.08375e+03]
 [3.96849e+03]
 [3.65242e+03]
 [3.07294e+03]
 [2.18894e+03]
 [9.37320e+02]
 [0.00000e+00]
 [2.38500e+01]
 [2.27460e+02]
 [1.04435e+03]
 [1.94028e+03]
 [2.16504e+03]
 [2.79295e+03]
 [3.86905e+03]
 [4.14119e+03]
 [4.06191e+03]
 [3.72135e+03]
 [3.12257e+03]
 [2.21717e+03]
 [9.57080e+02]
 [0.00000e+00]
 [5.57000e+00]
 [1.84550e+02]
 [1.12188e+03]
 [2.10933e+03]
 [3.08349e+03]
 [3.68710e+03]
 [3.98183e+03]
 [4.08503e+03]
 [3.91630e+03]
 [3.54570e

[[1.500000e-01]
 [8.513000e+01]
 [6.088500e+02]
 [3.002710e+03]
 [4.817210e+03]
 [6.545970e+03]
 [9.239280e+03]
 [8.812300e+03]
 [6.829240e+03]
 [7.746540e+03]
 [5.715890e+03]
 [5.699680e+03]
 [6.382300e+03]
 [2.826940e+03]
 [2.400000e-01]
 [7.252000e+01]
 [6.489000e+02]
 [2.347120e+03]
 [3.014930e+03]
 [5.823910e+03]
 [9.121160e+03]
 [9.847120e+03]
 [9.523810e+03]
 [9.901060e+03]
 [9.626030e+03]
 [8.232150e+03]
 [5.867410e+03]
 [2.975940e+03]
 [2.400000e-01]
 [5.018000e+01]
 [6.487200e+02]
 [1.688780e+03]
 [6.095730e+03]
 [8.316460e+03]
 [9.726700e+03]
 [1.002529e+04]
 [1.002581e+04]
 [1.002498e+04]
 [9.664470e+03]
 [8.232500e+03]
 [5.885220e+03]
 [2.995800e+03]
 [2.300000e-01]
 [8.256000e+01]
 [7.510700e+02]
 [3.176760e+03]
 [4.381730e+03]
 [5.276590e+03]
 [7.299460e+03]
 [9.765080e+03]
 [1.002498e+04]
 [1.002555e+04]
 [9.834760e+03]
 [8.376810e+03]
 [5.999430e+03]
 [3.035640e+03]
 [2.300000e-01]
 [4.778000e+01]
 [6.432900e+02]
 [2.805560e+03]
 [5.905970e+03]
 [8.172010e+03]
 [9.6532

[[0.00000e+00]
 [6.84000e+00]
 [1.05930e+02]
 [3.80600e+02]
 [5.73080e+02]
 [9.75740e+02]
 [1.25808e+03]
 [1.16832e+03]
 [1.77479e+03]
 [1.59304e+03]
 [1.44762e+03]
 [1.22100e+03]
 [8.61260e+02]
 [4.08230e+02]
 [0.00000e+00]
 [6.51000e+00]
 [9.99100e+01]
 [2.99910e+02]
 [5.77910e+02]
 [1.25700e+03]
 [1.14504e+03]
 [1.29454e+03]
 [1.25295e+03]
 [1.54180e+03]
 [1.58528e+03]
 [1.40396e+03]
 [1.03786e+03]
 [3.92650e+02]
 [0.00000e+00]
 [7.48000e+00]
 [7.22200e+01]
 [2.84430e+02]
 [7.00250e+02]
 [1.17433e+03]
 [1.64084e+03]
 [1.79250e+03]
 [1.83345e+03]
 [1.79242e+03]
 [1.62037e+03]
 [1.36187e+03]
 [1.01342e+03]
 [3.90080e+02]
 [0.00000e+00]
 [5.29000e+00]
 [5.00300e+01]
 [3.86040e+02]
 [9.62330e+02]
 [1.35869e+03]
 [1.64157e+03]
 [1.79826e+03]
 [1.84550e+03]
 [1.83908e+03]
 [1.70166e+03]
 [1.24158e+03]
 [9.94760e+02]
 [4.01970e+02]
 [0.00000e+00]
 [5.54000e+00]
 [6.37100e+01]
 [3.56700e+02]
 [6.47580e+02]
 [1.25593e+03]
 [1.64886e+03]
 [1.81128e+03]
 [1.86050e+03]
 [1.81406e+03]
 [1.65236e

[[0.000000e+00]
 [9.870000e+01]
 [5.888500e+02]
 [2.469460e+03]
 [5.236960e+03]
 [6.736850e+03]
 [1.047108e+04]
 [1.138147e+04]
 [8.216260e+03]
 [9.106560e+03]
 [6.911000e+03]
 [6.143700e+03]
 [6.597360e+03]
 [3.917560e+03]
 [0.000000e+00]
 [7.430000e+01]
 [7.109000e+02]
 [2.172520e+03]
 [3.008930e+03]
 [5.910100e+03]
 [1.077011e+04]
 [1.139599e+04]
 [1.220979e+04]
 [1.240219e+04]
 [1.180803e+04]
 [1.015089e+04]
 [7.650350e+03]
 [4.573320e+03]
 [0.000000e+00]
 [3.212000e+01]
 [2.739000e+02]
 [1.826380e+03]
 [7.222560e+03]
 [9.651540e+03]
 [1.112454e+04]
 [1.166722e+04]
 [1.191260e+04]
 [1.223175e+04]
 [1.159976e+04]
 [1.012949e+04]
 [7.642550e+03]
 [4.561260e+03]
 [0.000000e+00]
 [7.435000e+01]
 [4.330200e+02]
 [2.378550e+03]
 [5.957780e+03]
 [5.866470e+03]
 [8.569660e+03]
 [1.186205e+04]
 [1.239906e+04]
 [1.230515e+04]
 [1.171947e+04]
 [1.019613e+04]
 [7.776360e+03]
 [4.671820e+03]
 [0.000000e+00]
 [3.152000e+01]
 [3.155100e+02]
 [2.610590e+03]
 [6.939330e+03]
 [9.340060e+03]
 [1.0966

[[2.33000e+00]
 [2.98100e+01]
 [3.31540e+02]
 [1.09634e+03]
 [2.63535e+03]
 [4.01330e+03]
 [6.74790e+03]
 [7.09968e+03]
 [5.60224e+03]
 [6.35542e+03]
 [4.81564e+03]
 [4.91385e+03]
 [6.11732e+03]
 [3.90749e+03]
 [2.13000e+00]
 [3.79600e+01]
 [3.66390e+02]
 [1.19550e+03]
 [2.03902e+03]
 [3.45921e+03]
 [6.69785e+03]
 [7.70377e+03]
 [7.89209e+03]
 [7.98299e+03]
 [8.00289e+03]
 [7.81585e+03]
 [6.68769e+03]
 [4.75171e+03]
 [1.97000e+00]
 [1.67500e+01]
 [2.58940e+02]
 [1.21307e+03]
 [3.00123e+03]
 [5.11335e+03]
 [6.79022e+03]
 [7.77958e+03]
 [7.98495e+03]
 [7.98919e+03]
 [7.99583e+03]
 [7.82873e+03]
 [6.72177e+03]
 [4.78496e+03]
 [1.96000e+00]
 [3.90700e+01]
 [3.84500e+02]
 [1.12914e+03]
 [2.70508e+03]
 [3.59554e+03]
 [5.12050e+03]
 [7.55573e+03]
 [7.98694e+03]
 [7.99193e+03]
 [7.99900e+03]
 [7.86447e+03]
 [6.81278e+03]
 [4.80233e+03]
 [1.99000e+00]
 [1.48600e+01]
 [2.65860e+02]
 [1.52330e+03]
 [2.87965e+03]
 [4.97446e+03]
 [6.65383e+03]
 [7.70502e+03]
 [7.98730e+03]
 [7.97640e+03]
 [8.00695e

[[0.00000e+00]
 [1.58900e+01]
 [1.31260e+02]
 [6.69830e+02]
 [9.94510e+02]
 [1.42312e+03]
 [2.19722e+03]
 [2.03214e+03]
 [1.29862e+03]
 [1.76058e+03]
 [1.29922e+03]
 [1.15850e+03]
 [1.20417e+03]
 [6.25490e+02]
 [0.00000e+00]
 [1.09900e+01]
 [1.49770e+02]
 [5.02620e+02]
 [6.48720e+02]
 [1.23497e+03]
 [2.07818e+03]
 [2.47953e+03]
 [2.31319e+03]
 [2.56779e+03]
 [2.26783e+03]
 [1.71780e+03]
 [1.18858e+03]
 [5.47980e+02]
 [0.00000e+00]
 [5.17000e+00]
 [1.23910e+02]
 [3.96280e+02]
 [1.42024e+03]
 [1.98546e+03]
 [2.35716e+03]
 [2.56993e+03]
 [2.59824e+03]
 [2.53397e+03]
 [2.25438e+03]
 [1.83103e+03]
 [1.20348e+03]
 [5.57510e+02]
 [0.00000e+00]
 [1.36700e+01]
 [1.53990e+02]
 [6.99840e+02]
 [1.09901e+03]
 [1.26346e+03]
 [1.72768e+03]
 [2.48563e+03]
 [2.62141e+03]
 [2.55671e+03]
 [2.28892e+03]
 [1.86191e+03]
 [1.22178e+03]
 [5.63090e+02]
 [0.00000e+00]
 [3.60000e+00]
 [1.20640e+02]
 [6.78000e+02]
 [1.37393e+03]
 [1.94933e+03]
 [2.32958e+03]
 [2.54402e+03]
 [2.58985e+03]
 [2.45528e+03]
 [2.18456e

[[0.00000e+00]
 [5.78000e+00]
 [1.05090e+02]
 [8.75600e+01]
 [4.05810e+02]
 [9.83880e+02]
 [1.26011e+03]
 [1.17147e+03]
 [1.77257e+03]
 [1.59568e+03]
 [1.45361e+03]
 [1.24354e+03]
 [8.91050e+02]
 [4.80840e+02]
 [0.00000e+00]
 [5.89000e+00]
 [9.82900e+01]
 [2.48400e+02]
 [5.61110e+02]
 [1.26474e+03]
 [1.15364e+03]
 [1.30223e+03]
 [1.26268e+03]
 [1.55592e+03]
 [1.61361e+03]
 [1.44613e+03]
 [1.08570e+03]
 [6.28260e+02]
 [0.00000e+00]
 [5.88000e+00]
 [5.76100e+01]
 [2.73450e+02]
 [6.59410e+02]
 [1.19289e+03]
 [1.68483e+03]
 [1.83445e+03]
 [1.87513e+03]
 [1.82655e+03]
 [1.66087e+03]
 [1.40426e+03]
 [1.06149e+03]
 [6.25580e+02]
 [0.00000e+00]
 [3.87000e+00]
 [3.89900e+01]
 [1.44400e+02]
 [7.75900e+02]
 [1.40279e+03]
 [1.67476e+03]
 [1.82490e+03]
 [1.87199e+03]
 [1.85506e+03]
 [1.72645e+03]
 [1.26615e+03]
 [1.02986e+03]
 [6.25330e+02]
 [0.00000e+00]
 [0.00000e+00]
 [0.00000e+00]
 [7.17000e+01]
 [5.71880e+02]
 [1.27134e+03]
 [1.68591e+03]
 [1.85307e+03]
 [1.88884e+03]
 [1.84402e+03]
 [1.68995e

[[0.00000e+00]
 [3.96600e+01]
 [2.27980e+02]
 [1.60008e+03]
 [2.42501e+03]
 [2.04086e+03]
 [3.59486e+03]
 [4.36219e+03]
 [3.76231e+03]
 [3.10007e+03]
 [3.28252e+03]
 [2.23464e+03]
 [1.05438e+03]
 [4.08400e+02]
 [0.00000e+00]
 [1.21400e+01]
 [3.25320e+02]
 [7.08080e+02]
 [2.10536e+03]
 [2.83618e+03]
 [3.22240e+03]
 [2.51360e+03]
 [2.84133e+03]
 [3.06903e+03]
 [3.27091e+03]
 [2.55662e+03]
 [1.35495e+03]
 [5.34710e+02]
 [0.00000e+00]
 [2.00500e+01]
 [2.44950e+02]
 [1.41781e+03]
 [2.79123e+03]
 [4.14795e+03]
 [4.69298e+03]
 [4.76730e+03]
 [4.62464e+03]
 [4.19738e+03]
 [3.55371e+03]
 [2.60508e+03]
 [1.39809e+03]
 [3.65380e+02]
 [0.00000e+00]
 [1.51500e+01]
 [1.51430e+02]
 [1.44678e+03]
 [3.58447e+03]
 [4.35770e+03]
 [4.73108e+03]
 [4.81137e+03]
 [4.68656e+03]
 [4.16932e+03]
 [3.58114e+03]
 [2.43682e+03]
 [1.44666e+03]
 [4.38170e+02]
 [0.00000e+00]
 [1.68300e+01]
 [1.92270e+02]
 [1.52306e+03]
 [3.11181e+03]
 [2.79386e+03]
 [4.71287e+03]
 [4.87073e+03]
 [4.70749e+03]
 [4.22809e+03]
 [3.55646e

[[0.00000e+00]
 [3.61900e+01]
 [2.16220e+02]
 [7.47550e+02]
 [1.33460e+03]
 [2.08572e+03]
 [3.78542e+03]
 [4.72361e+03]
 [3.54278e+03]
 [4.04717e+03]
 [2.93378e+03]
 [2.82610e+03]
 [2.96926e+03]
 [1.83554e+03]
 [0.00000e+00]
 [2.76100e+01]
 [2.54430e+02]
 [6.75420e+02]
 [1.16127e+03]
 [2.07855e+03]
 [3.91035e+03]
 [4.75596e+03]
 [5.40005e+03]
 [5.46122e+03]
 [5.42735e+03]
 [4.88865e+03]
 [3.85420e+03]
 [2.34038e+03]
 [0.00000e+00]
 [1.23000e+01]
 [1.95970e+02]
 [7.18410e+02]
 [1.63282e+03]
 [2.89774e+03]
 [4.16437e+03]
 [4.89178e+03]
 [5.27198e+03]
 [5.52518e+03]
 [5.33847e+03]
 [4.87422e+03]
 [3.86829e+03]
 [2.34455e+03]
 [0.00000e+00]
 [2.46900e+01]
 [2.37710e+02]
 [7.70640e+02]
 [1.69371e+03]
 [2.03745e+03]
 [3.26145e+03]
 [4.73607e+03]
 [5.35479e+03]
 [5.53613e+03]
 [5.40406e+03]
 [4.93323e+03]
 [3.92601e+03]
 [2.40358e+03]
 [0.00000e+00]
 [1.16800e+01]
 [1.94700e+02]
 [1.02352e+03]
 [1.53877e+03]
 [2.80403e+03]
 [4.09321e+03]
 [4.77902e+03]
 [5.22982e+03]
 [5.26842e+03]
 [5.08562e

[[3.95000e+00]
 [2.98700e+01]
 [2.26270e+02]
 [8.04170e+02]
 [1.64137e+03]
 [2.49622e+03]
 [3.99603e+03]
 [4.34579e+03]
 [3.18407e+03]
 [3.88694e+03]
 [2.80690e+03]
 [2.90364e+03]
 [3.56301e+03]
 [1.88258e+03]
 [3.88000e+00]
 [2.89600e+01]
 [2.46360e+02]
 [7.71920e+02]
 [1.20502e+03]
 [2.09021e+03]
 [3.98745e+03]
 [4.73011e+03]
 [4.83401e+03]
 [4.99129e+03]
 [4.97507e+03]
 [4.54963e+03]
 [3.65306e+03]
 [2.37089e+03]
 [1.00000e-02]
 [2.08600e+01]
 [2.13950e+02]
 [7.41840e+02]
 [1.83777e+03]
 [3.08086e+03]
 [4.06834e+03]
 [4.74154e+03]
 [4.98879e+03]
 [4.99158e+03]
 [4.98006e+03]
 [4.56784e+03]
 [3.65577e+03]
 [2.38284e+03]
 [3.00000e-02]
 [3.19300e+01]
 [2.71340e+02]
 [8.38950e+02]
 [1.66754e+03]
 [2.21000e+03]
 [3.16302e+03]
 [4.61883e+03]
 [4.98956e+03]
 [4.99177e+03]
 [4.98360e+03]
 [4.58880e+03]
 [3.71218e+03]
 [2.40438e+03]
 [2.00000e-02]
 [1.82000e+01]
 [2.15650e+02]
 [9.89590e+02]
 [1.77578e+03]
 [3.00441e+03]
 [4.02163e+03]
 [4.69041e+03]
 [4.98416e+03]
 [4.95488e+03]
 [4.85146e

In [70]:
tcn_mase_ts, tcn_dist_ts, mase_vals_cnn = get_results_ts('cnn_results/tcn')

plot error in chart

In [154]:
fig = go.Figure(data=[
    go.Bar(name='LSTM', x=const.TS, y=mase_vals_lstm),
    go.Bar(name='Dilated Convolutions', x=const.TS, y=mase_vals_cnn)
])
# Change the bar mode
fig.update_layout(barmode='group')
fig.update_layout(title='Mean MASE - 36 samples (1 day ahead - 1 hour resolution)')
fig.show()

Error distributions

In [155]:
fig = go.Figure()
for col in lstm_dist_ts.keys():
    box_data = lstm_dist_ts[col]
    fig.add_trace(go.Box(y=box_data, name = col))
fig.update_xaxes(title = 'Time series')
fig.update_yaxes(title = 'MASE distribution')
fig.update_layout(title = "LSTM")

In [79]:
fig = go.Figure()
for col in tcn_dist_ts.keys():
    box_data = tcn_dist_ts[col]
    fig.add_trace(go.Box(y=box_data, name = col))
fig.update_xaxes(title = 'Time series')
fig.update_yaxes(title = 'MASE distribution')
fig.update_layout(title = "Dilated Convolutions")

## Errors at each level

In [86]:
def get_fc_each_level(start, end, mase_dict):
    ts_names = const.TS[start: end]
    mase_vals= []
    for ts in ts_names: 
        mase_vals.append(mase_dict[ts])
    avg_mase = np.mean(mase_vals)
    return avg_mase

In [96]:
def get_fc_error_level_model(model_mase_dic):
    level_mase = []
    grid = get_fc_each_level(0, 1, model_mase_dic)
    tl_line = get_fc_each_level(1, 3, model_mase_dic)
    sub = get_fc_each_level(3, 7, model_mase_dic)
    pc = get_fc_each_level(7, 13, model_mase_dic)
    site = get_fc_each_level(13, -1, model_mase_dic)
    level_mase.append(grid)
    level_mase.append(tl_line)
    level_mase.append(sub)
    level_mase.append(pc)
    level_mase.append(site)
    return level_mase

In [97]:
level_results_lstm = get_fc_error_level_model(lstm_dist_ts)

In [98]:
level_results_lstm

[1.4682344960050517,
 1.2524747891070842,
 1.0567580109364902,
 0.812090928778454,
 0.8593696732847954]

In [99]:
level_results_tcn = get_fc_error_level_model(tcn_dist_ts)

In [103]:
x_vals = ['grid', 'tl', 'sub', 'postcode', 'site']
fig = go.Figure(data=[
    go.Bar(name='LSTM', x=x_vals, y=level_results_lstm),
    go.Bar(name='Dilated Convolutions', x=x_vals, y=level_results_tcn)
])
# Change the bar mode
fig.update_layout(barmode='group')
fig.update_layout(title='Avergae MASE at each level - 36 samples per timeseries (1 day ahead - 1 hour resolution)')
fig.show()

## Grid level Forecasts

In [144]:
def sum_fc_results(ts_array, model_path):
    dfs = []
    for ts in ts_array:
        ts_fc = pd.read_csv(f'../{model_path}/final_results/{ts}.csv', index_col=[0])[['average_fc']]
        dfs.append(ts_fc)
    concat_df = pd.concat(dfs, axis=1).sum(axis=1)
    return concat_df

In [161]:
def calculate_grid_error(start, end, model_path):
    ts_array = const.TS[start: end]
    data = pd.read_csv(f'../ts_data/grid.csv', index_col=[0])
    look_back = 14 * 7  # 14 hours in to 7 days

    # train, val, test split
    train, val, test = util.split_hourly_data(data, look_back)
    train_df = train[['power']]
    denom = err.calculate_denom(train_df, const.H_SEASONALITY)
    
    results_df = pd.read_csv(f'../{model_path}/final_results/grid.csv', index_col=[0])
    test_sample = results_df['power'].values
    forecasts = sum_fc_results(ts_array, model_path).values
    horizon = 14
    
    mean_mase, error_dist = err.test_errors(train_df, test_sample, forecasts, horizon, const.H_SEASONALITY, denom)
    return mean_mase, error_dist

In [162]:
def mase_grid(model_path):
    level_mase = []
    level_mase_dist = {}
    grid_mase, grid_dist = calculate_grid_error(0, 1, model_path)
    tl_mase, tl_dist = calculate_grid_error(1, 3, model_path)
    sub_mase, sub_dist = calculate_grid_error(3, 7, model_path)
    pc_mase, pc_dist = calculate_grid_error(7, 13, model_path)
    site_mase, site_dist = calculate_grid_error(13, -1, model_path)
    
    level_mase.append(grid_mase)
    level_mase.append(tl_mase)
    level_mase.append(sub_mase)
    level_mase.append(pc_mase)
    level_mase.append(site_mase)
    
    
    level_mase_dist['grid'] = grid_dist
    level_mase_dist['tl'] = tl_dist
    level_mase_dist['sub'] = sub_dist
    level_mase_dist['pc'] = pc_dist
    level_mase_dist['site'] = site_dist
    
    return level_mase, level_mase_dist

In [163]:
grid_error, grid_error_dist = mase_grid('lstm_results')

In [165]:
grid_error_tcn, grid_error_dist_tcn = mase_grid('cnn_results/tcn')

In [167]:
x_vals = ['grid', 'tl', 'sub', 'postcode', 'site']
fig = go.Figure(data=[
    go.Bar(name='LSTM', x=x_vals, y=grid_error),
    go.Bar(name='Dilated Convolutions', x=x_vals, y=grid_error_tcn)
])
# Change the bar mode
fig.update_layout(barmode='group')
fig.update_layout(title='Grid level forecasts - Mean MASE (1 day ahead - 1 hour resolution)')
fig.show()

In [169]:
fig = go.Figure()
for col in grid_error_dist.keys():
    box_data = grid_error_dist[col]
    fig.add_trace(go.Box(y=box_data, name = col))
fig.update_xaxes(title = 'BU strategy - ts hierarchy level')
fig.update_yaxes(title = 'MASE distribution')
fig.update_layout(title = "Grid level forecasts - Model LSTM")

In [170]:
fig = go.Figure()
for col in grid_error_dist_tcn.keys():
    box_data = grid_error_dist_tcn[col]
    fig.add_trace(go.Box(y=box_data, name = col))
fig.update_xaxes(title = 'BU strategy - ts hierarchy level')
fig.update_yaxes(title = 'MASE distribution')
fig.update_layout(title = "Grid level forecasts - Model Dilated Convolutions")